import {Action} from "redux";

export enum ActionModalActions {
    OPEN_SHARE_MODAL="OPEN_SHARE_MODAL",
    OPEN_REVEAL_MODAL="OPEN_REVEAL_MODAL",
    OPEN_NOMINATE_LEADER_MODAL="OPEN_NOMINATE_LEADER_MODAL",
    CLOSE_MODAL="CLOSE_MODAL",
}

export enum GameAction {
    CONNECTED="CONNECTED",
    DISCONNECTED="DISCONNECTED",
    CREATE_GAME="CREATE_GAME",
    JOIN_GAME = "JOIN_GAME",
    RELOAD_GAME_SESSION = "RELOAD_GAME_SESSION",
    HIDE_ERROR = "HIDE_ERROR",
    START_GAME = "START_GAME",
    NEXT_ROUND = "NEXT_ROUND",
    START_TIMER = "START_TIMER",
    PAUSE_TIMER = "PAUSE_TIMER",
    RESTART_TIMER = "RESTART_TIMER",
    REQUEST_SHARE = "REQUEST_SHARE",
    ACCEPT_SHARE = "ACCEPT_SHARE",
    REJECT_SHARE = "REJECT_SHARE",
    PRIVATE_REVEAL = "PRIVATE_REVEAL",
    RESPOND_TO_EVENT = "RESPOND_TO_EVENT",
    DISMISS_EVENT = "DISMISS_EVENT",
    REVEAL_CARD_ASSIGNMENT = "REVEAL_CARD_ASSIGNMENT",
    NOMINATE_LEADER = "NOMINATE_LEADER",
    NOMINATE_HOSTAGE = "NOMINATE_HOSTAGE",
    ABDICATE_AS_LEADER = "ABDICATE_AS_LEADER",
    ANSWER_LEADERSHIP_OFFER = "ANSWER_LEADERSHIP_OFFER",
    USURP_LEADER = "USURP_LEADER",
    USURP_VOTE = "USURP_VOTE",
    OTHER_ACTION = "__any_other_action_type__",
}

export enum RevealActions {
    DO_REVEAL = "DO_REVEAL",
    CLEAR_REVEAL = "CLEAR_REVEAL"
}

export enum NotificationActions {
    CLOSE_SNACKBAR = "CLOSE_SNACKBAR",
    REMOVE_SNACKBAR = "REMOVE_SNACKBAR"
}

export interface SocketAction extends Action {
    type: GameAction,
    meta: {
        remote: boolean,
        isGameRequest?: boolean
    },
    payload: Object
}