package me.ajfleming.tworoomsio.socket.event;

public enum UserEvents {
	RELOAD_GAME_SESSION,
	JOIN_GAME,
	REQUEST_SHARE,
	ACCEPT_SHARE,
	REJECT_SHARE,
	PRIVATE_REVEAL,
	NOMINATE_LEADER,
	NOMINATE_HOSTAGE,
	ADBICATE_AS_LEADER,
	ANSWER_LEADERSHIP_OFFER,
	USURP_LEADER,
	USURP_VOTE
}
