export enum Listeners {
    JOIN_GAME_SUCCESS= "JOIN_GAME_SUCCESS",
    JOIN_GAME_ERROR = "JOIN_GAME_ERROR",
    GAME_UPDATE = "GAME_UPDATE",
    CARD_UPDATE = "CARD_UPDATE",
    TIMER_UPDATE = "TIMER_UPDATE",
    RELOAD_GAME_SESSION_SUCCESS = "RELOAD_GAME_SESSION_SUCCESS",
    RELOAD_GAME_SESSION_ERROR = 'RELOAD_GAME_SESSION_ERROR',
    REQUEST_SHARE_SUCCESS = "REQUEST_SHARE_SUCCESS",
    REQUEST_SHARE_ERROR = "REQUEST_SHARE_ERROR",
    SHARE_REQUEST_RECEIVED = "SHARE_REQUEST_RECEIVED",
    SHARE_REQUEST_REJECTED = "SHARE_REQUEST_REJECTED",
    REJECT_SHARE_SUCCESS = "REJECT_SHARE_SUCCESS",
    CARD_SHARE_ACCEPTED = "CARD_SHARE_ACCEPTED",
    PRIVATE_REVEAL_RECEIVED = "PRIVATE_REVEAL_RECEIVED",
    ANSWER_SHARE_ERROR = "ANSWER_SHARE_ERROR",
    CLEAR_EVENTS = "CLEAR_EVENTS",
    ROOM_UPDATE = "ROOM_UPDATE"
}

export const actionListeners = () => {
    let enumValues:Array<string> = [];

    for(let value in Listeners) {
        enumValues.push( value );
    }

    return enumValues;
}