package me.ajfleming.tworoomsio.socket;

import lombok.Getter;

@Getter
public enum Event {
  JOIN_GAME("JOIN_GAME"),
  JOIN_GAME_SUCCESS("JOIN_GAME_SUCCESS"),
  JOIN_GAME_ERROR("JOIN_GAME_ERROR"),
  RELOAD_GAME_SESSION("RELOAD_GAME_SESSION"),
  RELOAD_GAME_SESSION_SUCCESS("RELOAD_GAME_SESSION_SUCCESS"),
  RELOAD_GAME_SESSION_ERROR("RELOAD_GAME_SESSION_ERROR"),
  NEXT_ROUND("NEXT_ROUND"),
  START_TIMER("START_TIMER"),
  PAUSE_TIMER("PAUSE_TIMER"),
  REQUEST_SHARE("REQUEST_SHARE"),
  ACCEPT_SHARE("ACCEPT_SHARE"),
  REJECT_SHARE("REJECT_SHARE"),
  PRIVATE_REVEAL("PRIVATE_REVEAL");

  private final String value;

  Event(String value) {
    this.value = value;
  }
}
